import { integer, real, sqliteTable, text, uniqueIndex } from "drizzle-orm/sqlite-core";

export const rules = sqliteTable("rules", {
  key: text("key").primaryKey(),
  category: text("category").notNull(),
  name: text("name").notNull(),
  parentKey: text("parent_key"),
  level: integer("level"),
  sortOrder: integer("sort_order").notNull().default(0),
  dataJson: text("data_json").notNull(),
  sourceVersion: text("source_version").notNull(),
});

export const classResources = sqliteTable("class_resources", {
  key: text("key").primaryKey(),
  classKey: text("class_key").notNull(),
  subclassKey: text("subclass_key"),
  name: text("name").notNull(),
  shortName: text("short_name").notNull(),
  levelAvailable: integer("level_available").notNull(),
  maxFormula: text("max_formula").notNull(),
  recovery: text("recovery").notNull(),
  sortOrder: integer("sort_order").notNull().default(0),
  dataJson: text("data_json").notNull(),
  sourceVersion: text("source_version").notNull(),
});

export const customClasses = sqliteTable("custom_classes", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  key: text("key").notNull().unique(),
  ownerKey: text("owner_key").notNull().default(""),
  name: text("name").notNull(),
  hitDie: integer("hit_die").notNull(),
  savingThrowsJson: text("saving_throws_json").notNull(),
  skillChoicesJson: text("skill_choices_json").notNull(),
  skillChoiceCount: integer("skill_choice_count").notNull(),
  toolProficiencies: text("tool_proficiencies").notNull().default(""),
  armorProficiencies: text("armor_proficiencies").notNull().default(""),
  weaponProficiencies: text("weapon_proficiencies").notNull().default(""),
  startingEquipment: text("starting_equipment").notNull().default(""),
  featuresJson: text("features_json").notNull(),
  spellcastingProgression: text("spellcasting_progression").notNull().default("none"),
  spellcastingAbility: text("spellcasting_ability"),
  resourceName: text("resource_name"),
  resourceAmountsJson: text("resource_amounts_json"),
  resourceRecovery: text("resource_recovery"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const customSpecies = sqliteTable("custom_species", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  key: text("key").notNull().unique(),
  ownerKey: text("owner_key").notNull().default(""),
  name: text("name").notNull(),
  creatureType: text("creature_type").notNull(),
  size: text("size").notNull(),
  speed: integer("speed").notNull(),
  traitsJson: text("traits_json").notNull(),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const customSubclasses = sqliteTable("custom_subclasses", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  key: text("key").notNull().unique(),
  ownerKey: text("owner_key").notNull().default(""),
  classKey: text("class_key").notNull(),
  name: text("name").notNull(),
  featuresJson: text("features_json").notNull(),
  resourceName: text("resource_name"),
  resourceSize: integer("resource_size"),
  resourceRecovery: text("resource_recovery"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const characterSpells = sqliteTable("character_spells", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  characterId: integer("character_id").notNull(),
  spellName: text("spell_name").notNull(),
  inSpellbook: integer("in_spellbook", { mode: "boolean" }).notNull().default(false),
  prepared: integer("prepared", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
}, (table) => [uniqueIndex("character_spells_character_name_unique").on(table.characterId, table.spellName)]);

export const characterInventory = sqliteTable("character_inventory", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  characterId: integer("character_id").notNull(),
  itemKey: text("item_key").notNull(),
  itemName: text("item_name").notNull(),
  category: text("category").notNull(),
  quantity: integer("quantity").notNull().default(1),
  equipped: integer("equipped", { mode: "boolean" }).notNull().default(false),
  weightLb: real("weight_lb"),
  armorDataJson: text("armor_data_json").notNull().default("{}"),
  weaponDataJson: text("weapon_data_json").notNull().default("{}"),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});

export const characters = sqliteTable("characters", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  ownerKey: text("owner_key").notNull().default(""),
  name: text("name").notNull(),
  speciesKey: text("species_key").notNull(),
  classKey: text("class_key").notNull(),
  classHitDie: integer("class_hit_die"),
  subclassKey: text("subclass_key"),
  backgroundKey: text("background_key").notNull(),
  level: integer("level").notNull().default(1),
  xp: integer("xp").notNull().default(0),
  abilityScoresJson: text("ability_scores_json").notNull(),
  skillProficienciesJson: text("skill_proficiencies_json").notNull(),
  maxHp: integer("max_hp").notNull(),
  currentHp: integer("current_hp").notNull(),
  tempHp: integer("temp_hp").notNull().default(0),
  gearText: text("gear_text").notNull().default(""),
  notesText: text("notes_text").notNull().default(""),
  otherNotesText: text("other_notes_text").notNull().default(""),
  appearanceText: text("appearance_text").notNull().default(""),
  backstoryText: text("backstory_text").notNull().default(""),
  alliesText: text("allies_text").notNull().default(""),
  additionalFeaturesText: text("additional_features_text").notNull().default(""),
  treasureText: text("treasure_text").notNull().default(""),
  avatarKey: text("avatar_key"),
  customAvatarBlobKey: text("custom_avatar_blob_key"),
  gearMigrated: integer("gear_migrated", { mode: "boolean" }).notNull().default(false),
  currencyJson: text("currency_json").notNull().default('{"cp":0,"sp":0,"ep":0,"gp":0,"pp":0}'),
  resourceStateJson: text("resource_state_json").notNull().default("{}"),
  hitDiceSpent: integer("hit_dice_spent").notNull().default(0),
  concentrationSpellName: text("concentration_spell_name"),
  conditionsJson: text("conditions_json").notNull().default("[]"),
  exhaustionLevel: integer("exhaustion_level").notNull().default(0),
  arcaneRecoveryUsed: integer("arcane_recovery_used", { mode: "boolean" }).notNull().default(false),
  sorcerousRestorationUsed: integer("sorcerous_restoration_used", { mode: "boolean" }).notNull().default(false),
  createdAt: integer("created_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
  updatedAt: integer("updated_at", { mode: "timestamp_ms" }).notNull().$defaultFn(() => new Date()),
});